VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('20')
VERSION_HOUR = int('05')
VERSION_MINUTE = int('36')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202211200536
version_date = '2022/11/20 05:36'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
