VERSION_YEAR = 2022
VERSION_MONTH = int('11')
VERSION_DAY = int('18')
VERSION_HOUR = int('00')
VERSION_MINUTE = int('30')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202211180030
version_date = '2022/11/18 00:30'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
